### ISSUE TITLE
Hardware Enviroment

### ISSUE THREAD

**Issue by HuCutie** [thu-ml/Attack-Bard#2]
Hi, thank you for your contributions in this filed! 
I wonder which  GPU(s) you have used in this project? Cause I see "Text description attack against Bard's image description." you just use 1 GPU in this phase.

**Comment by huanranchen** [comment]
Hi~ Thank you for your interest!
The GPU requirement is:
image embedding attack: about 40G (We use 3x3090 GPU)
vlm attack: (depends on surrogate models. Minigpt4: about 24G. InstructBlip: about 32G. Blip2: about 24G) (We use 1xA100 GPU)

We also provide some crafted adversarial examples here https://github.com/thu-ml/Attack-Bard/tree/main/dataset/ssa-cwa-200

For more detail, please refer to https://github.com/thu-ml/Attack-Bard/issues/1
