### ISSUE TITLE
Why do images need to be normalized?

### ISSUE THREAD

**Issue by RylanSchaeffer** [thu-ml/Attack-Bard#6]
I noticed that there's a normalizer for images:

https://github.com/thu-ml/Attack-Bard/blob/main/surrogates/Blip2.py#L34-L39

This normalizer is then used before images are fed into the model:

https://github.com/thu-ml/Attack-Bard/blob/main/surrogates/Blip2.py#L48-L50

But if I look at the BLIP2 usage examples, e.g., https://huggingface.co/docs/transformers/main/en/model_doc/blip-2#transformers.Blip2Model.forward.example, there's no usage of any normalizer:

```
processor = Blip2Processor.from_pretrained("Salesforce/blip2-opt-2.7b")
model = Blip2Model.from_pretrained("Salesforce/blip2-opt-2.7b", torch_dtype=torch.float16)
model.to(device)
url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open(requests.get(url, stream=True).raw)
prompt = "Question: how many cats are there? Answer:"
inputs = processor(images=image, text=prompt, return_tensors="pt").to(device, torch.float16)
outputs = model(**inputs)
```

Why is a normalizer used here? Why is the preprocessor not used?

**Comment by huanranchen** [comment]
Hi, this is because the normalizer is inside "Blip2Processor". However, this preprocessor is not differentiable, the gradient cannot backpropagate through this preprocessor. Hence, we have to rewrite this by ourselves to make it differentiable.

**Comment by RylanSchaeffer** [comment]
Ok thank you!
